import { ReactNode } from 'react';

export const metadata = {
    title: 'Makey Siong | About',
    description: 'Generated by Next.js',
};

type ContactLayoutProps = {
    children: ReactNode;
};

export default function ContactLayout({ children }: ContactLayoutProps) {
    return (
        <div>
            {children}
        </div>
    );
}
