import { ReactNode } from 'react';

export const metadata = {
    title: 'Makey Siong | About',
    description: 'Generated by Next.js',
};

type AboutLayoutProps = {
    children: ReactNode;
};

export default function AboutLayout({ children }: AboutLayoutProps) {
    return (
        <div>
            {children}
        </div>
    );
}
