import { ReactNode } from 'react';

export const metadata = {
    title: 'Makey Siong | Portfolio',
    description: 'Generated by Next.js',
};

type PortfolioLayoutProps = {
    children: ReactNode;
};

export default function PortfolioLayout({ children }: PortfolioLayoutProps) {
    return (
        <div>
            {children}
        </div>
    );
}
