import React from 'react';
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import GlobalStyle from "./GlobalStyle";

export const metadata = {
  title: 'Makey Siong | Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
        <link
          rel="icon"
          href="/mk_vision.png"
          type="image/png"
        />
      </head>
      <body>
        <GlobalStyle />
        <header><NavBar /></header>
        <main>
          {children}
        </main>
        <footer><Footer /></footer>
      </body>
    </html>
  );
}
